version: '3.5'

services:
  mongo-payment:
    container_name: mongo_payment_container
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - payment-network
    volumes:
      - mongo_payment_data:/data/db

  mongo-express:
    container_name: mongo_express_payment
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-payment
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - payment-network
    depends_on:
      - mongo-payment

networks:
  payment-network:
    driver: bridge

volumes:
  mongo_payment_data:
