version: '3.5'

services:
  postgres-video:
    container_name: postgres_video_container
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-postgres-api-order}
      PGDATA: /data/postgres
    volumes:
      - postgres_order:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - order-network
    restart: unless-stopped

networks:
  payment-network:
    driver: bridge

volumes:
  mongo_payment_data:
