server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: payment-db
      uri: mongodb://localhost:27017/payment-api

  messages:
    basename: messages
    encoding: UTF-8

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always