server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.web: DEBUG
    com.processvideoapi: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      endpoint: http://localhost:4566
      s3:
        bucket: video-uploads
        path-style-access-enabled: true

  messages:
    basename: messages
    encoding: UTF-8

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always