spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.web: DEBUG
    com.processvideoapi: DEBUG

  messages:
    basename: messages
    encoding: UTF-8

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always